@startuml

entity "ユーザー" {
  *ユーザーID
  ---
  -ユーザー名
  -ログインID
  -パスワード
  -最終ログイン日時
  -アカウント作成日
  -支払い方法
  -会員ステータス
}

entity "視聴履歴" {
  *視聴履歴ID
  ---
  *ユーザーID<<FK>>
  *エピソードID<<FK>>
  -視聴日時
}

entity "ダウンロード" {
  *ダウンロードID
  ---
  *ユーザーID<<FK>>
  *エピソードID<<FK>>
}

entity "マイリスト" {
  *マイリストID
  ---
  *ユーザーID<<FK>>
  *番組ID<<FK>>
}

entity "チャンネル"{
  *チャンネルID
  ---
  -チャンネル名
}

entity "番組"{
  *番組ID
  ---
  *チャンネルID<<FK>>
  -番組タイトル名
  -番組詳細
  -番組シーズン数
  -エピソード数
  -番組視聴回数
}

entity "番組シーズン"{
  *番組シーズンID
  ---
  *番組ID<<FK>>
  -番組シーズン名
  -エピソード数
}

entity "プログラム-番組"{
  *プログラム-番組ID
  ---
  *プログラムID<<FK>>
  *番組ID<<FK>>
}

entity "ジャンル"{
  *ジャンルID
  ---
  -ジャンル名
}

entity "エピソード"{
  *エピソードID
  ---
  *番組ID<<FK>>
  *チャンネルID<<FK>>
  -エピソードタイトル名
  -動画時間
  -公開日
  -エピソード視聴回数
  -グッド評価
  -放送開始時刻
  -放送終了時刻
}

entity "エピソード詳細"{
  *エピソード詳細ID
  ---
  *エピソードID<<FK>>
  エピソード詳細文
}

entity "キャスト"{
  *キャストID
  ---
  *エピソード詳細ID<<FK>>
  -キャスト名

}

"ユーザー" ||--o{ "視聴履歴"
"ユーザー" ||--o{ "ダウンロード"
"ユーザー" ||--o{ "マイリスト"
"チャンネル" ||--o{ "番組"
"番組" ||--o{ "エピソード"
"番組" }o--||"プログラム-番組"
"プログラム-番組" ||--o{ "ジャンル"
"番組" ||--o{ "番組シーズン"
"エピソード" ||--|| "エピソード詳細"
"エピソード詳細" ||--o{ "キャスト"
"視聴履歴" ||--o{ "エピソード"
"ダウンロード" ||--o{ "エピソード"
"マイリスト" ||--o{ "番組"

@enduml

episodesテーブルにprogram_idというカラムを追加し、そのカラムに外部キー制約を設ける